generic:
  containersUnderTest:
    - namespace: tnf
      podName: test
      containerName: test
      defaultNetworkDevice: eth0
      multusIpAddresses:
        - 10.217.0.8
  partnerContainers:
    - namespace: tnf
      podName: partner
      containerName: partner
      defaultNetworkDevice: eth0
      multusIpAddresses:
        - 10.217.0.29
    - namespace: tnf
      podName: node-master
      containerName: master
      defaultNetworkDevice: eth0
  fsDiffMasterContainer:
    namespace: tnf
    podName: node-master
    containerName: master
  testOrchestrator:
    namespace: tnf
    podName: partner
    containerName: partner
operators:
  - name: etcdoperator.v0.9.4
    namespace: default
    autogenerate: false
    tests:
      - OPERATOR_STATUS
    certifiedoperatorrequestinfo:
      - name: "etcd-operator"
        organization: "redhat-marketplace"
cnfs:
  - name: ubuntu
    namespace: default
    tests:
      - PRIVILEGED_POD
      - PRIVILEGED_ROLE
    certifiedcontainerrequestinfo:
      - name: nginx-116  # working example
        repository: rhel8