generic:
  containersUnderTest:
    - namespace: tnf
      podName: test
      containerName: test
      defaultNetworkDevice: eth0
      multusIpAddresses:
        - 10.217.0.8
  partnerContainers:
    - namespace: tnf
      podName: partner
      containerName: partner
      defaultNetworkDevice: eth0
      multusIpAddresses:
        - 10.217.0.29
  testOrchestrator:
    namespace: tnf
    podName: partner
    containerName: partner
operators:
  - name: etcdoperator.v0.9.4
    namespace: default
    subscriptionName: etcd
    autogenerate: false
    tests:
      - OPERATOR_STATUS
cnfs:
  - name: ubuntu
    namespace: default
    tests:
      - PRIVILEGED_POD
      - PRIVILEGED_ROLE
certifiedcontainerinfo:
  - name: nginx-116  # working example
    repository: rhel8
certifiedoperatorinfo:
  - name: etcd-operator
    organization: redhat-marketplace