apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node-master
  name: node-master
  namespace: tnf
spec:
  # hostPID: true
  containers:
    - command:
        - tail
        - -f
        - /dev/null
      image: quay.io/isaacdorfman/centos-docker
      name: master
      resources:
        limits:
          memory: 512Mi
          cpu: 0.25
      volumeMounts:
      - mountPath: /var/lib/containers
        name: var-lib-containers
      - mountPath: /var/run/containers
        name: var-run-containers
      - mountPath: /run/runc
        name: runc-dir
      - mountPath: /var/run/containers/storage/overlay-containers
        name: overlay-containers
      securityContext:
        privileged: true
  restartPolicy: Always
  volumes:
  - name: var-lib-containers
    hostPath:
      path: /var/lib/containers
      type: Directory
  - name: var-run-containers
    hostPath:
      path: /var/run/containers
      type: Directory
  - name: runc-dir
    hostPath:
      path: /run/runc
      type: Directory
  - name: overlay-containers
    hostPath: 
      path: /var/run/containers/storage/overlay-containers
      type: Directory