operators:
  - name: jenkins-operator.0.7.1
    namespace: default
    autogenerate: false
    tests:
      - OPERATOR_STATUS
    certifiedoperatorrequestinfo:
      - name: amq-streams  #just a working example
        organization: redhat-operators
cnfs:
  - name: test
    namespace: default
    tests:
      - PRIVILEGED_POD
      - PRIVILEGED_ROLE
    certifiedcontainerrequestinfo:
      - name: nginx-116  # working example
        repository: rhel8