operators:
  - name: etcdoperator.v0.9.4
    namespace: my-etcd
    status: Succeeded
    autogenerate: false
    tests:
      - OPERATOR_STATUS
    certifiedoperatorrequestinfo:
      - name: amq-streams  #just a working example
        organization: redhat-operators
cnfs:
  - name: ubuntu
    namespace: default
    status: Running
    tests:
      - PRIVILEGED_POD
      - PRIVILEGED_ROLE
    certifiedcontainerrequestinfo:
      - name: nginx-116  # working example
        repository: rhel8
        certificatetype: CONTAINER