podUnderTest:
  name: "test"
  namespace: "default"
  containerConfiguration:
    name: "test"
    defaultNetworkDevice: "eth0"
    multusIPAddresses:
      - "192.168.2.1"
partnerPod:
  name: "partner"
  namespace: "default"
  containerConfiguration:
    name: "partner"
    defaultNetworkDevice: "eth0"
    multusIPAddresses:
      - "192.168.2.3"