name: build

on:
  pull_request:
    types: [ closed ]

jobs:

  build:
    if: github.event.pull_request.merged == true
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Rebuild mocks
        run: go get github.com/golang/mock/mockgen && make mocks

      - name: Run Tests
        run: make test

  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been closed without being merged

